Repository SKNIW/plan-backend, pull requests merged in 2022-11, with the labels that each got.

#23 #6 - scraping the timetable
  .docker/php/Dockerfile
  app/Console/Commands/ScrapTimetable.php
  app/Console/Kernel.php
  app/Dto/.gitignore
  app/Dto/LegendDto.php
  app/Models/Legend.php
  app/Models/Specialization.php
  app/Models/Timetable.php
  app/Spiders/Items/LegendItem.php
  app/Spiders/Items/TimetableItem.php
  app/Spiders/LegendSpider.php
  app/Spiders/Processors/LegendProcessor.php
  app/Spiders/Processors/TimetableProcessor.php
  app/Spiders/Spider.php
  app/Spiders/TimetableSpider.php
  app/Spiders/Utils/Constants.php
  composer.lock
  database/migrations/2022_11_13_090938_create_timetable.php
  public/vendor/horizon/app-dark.css
  public/vendor/horizon/app.css
  public/vendor/horizon/app.js
  public/vendor/horizon/mix-manifest.json
Labels: feature

#24 #7 - job scheduler for scraping sites
  .env.example
  Makefile
  app/Console/Commands/ScrapFaculties.php
  app/Console/Commands/ScrapLegend.php
  app/Console/Commands/ScrapTimetable.php
  app/Console/Kernel.php
  app/Jobs/AbstractJob.php
  app/Jobs/ScheduleScrapingTimetable.php
  app/Jobs/SpecializationJob.php
  app/Jobs/TimetableJob.php
  app/Models/Timetable.php
  app/Providers/HorizonServiceProvider.php
  app/Service/AbstractBatchingService.php
  app/Service/Exception/BatchException.php
  app/Service/TimetableService.php
  app/Services/.gitignore
  app/Spiders/LegendSpider.php
  app/Spiders/Processors/TimetableProcessor.php
  app/Spiders/TimetableSpider.php
  app/Spiders/Utils/Constants.php
  composer.json
  composer.lock
  config/app.php
  config/horizon.php
  config/queue.php
  database/migrations/2022_11_13_090938_create_timetable.php
  database/migrations/2022_11_13_153607_create_job_batches_table.php
Labels: feature

#26 #13 - setup dockerfile for prod and pipeline
  .docker/php/Dockerfile
  .docker/php/Dockerfile-dev
  .docker/php/bin/entrypoint.sh
  .github/workflows/php.yml
  docker-compose.yml
Labels: infrastructure

#27 #4 - fix specialization scraping
  app/Models/Field.php
  app/Spiders/FacultySpider.php
  app/Spiders/Items/FieldItem.php
  app/Spiders/Processors/FieldProcessor.php
  app/Spiders/Utils/Constants.php
  database/migrations/2022_10_25_191646_create_fields_table.php
Labels: bug

#29 #13 - optimaze dockerfile
  .docker/php/Dockerfile
  .docker/php/Dockerfile-dev
  .docker/php/bin/entrypoint.sh
  .docker/php/conf/opcache.ini
  .docker/php/conf/php-fpm.conf
  docker-compose.yml
Labels: infrastructure

#31 #8 - remove laravel magic
  app/Http/Controllers/FacultyController.php
  app/Http/Controllers/FieldController.php
  app/Http/Controllers/SpecializationController.php
  app/Models/Exceptions/FacultyNotFoundException.php
  app/Models/Exceptions/FieldNotFoundException.php
  app/Models/Exceptions/SpecializationNotFoundException.php
  app/Models/Faculty.php
  app/Models/Field.php
  app/Models/Specialization.php
  app/Services/Api/FacultyService.php
  app/Services/Api/FieldService.php
  app/Services/Api/SpecializationService.php
  config/request-docs.php
  docs/request-docs/index.html
  docs/request-docs/lrd-openapi.json
  routes/api.php
Labels: bug, documentation

#33 #30 - add new libary documentation
  README.md
  app/Exceptions/Handler.php
  app/Exceptions/NotFoundEnvException.php
  composer.json
  composer.lock
  config/request-docs.php
  config/scramble.php
  docs/request-docs/index.html
  docs/request-docs/lrd-openapi.json
Labels: documentation
